---
# Move this to apps folder to run the grafana and prometheus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 68.3.0
    chart: kube-prometheus-stack
    helm:
      version: v3
      releaseName: promstack
      valueFiles:
        - $values/environments/sandbox/monitoring/values.yaml
  - repoURL: 'https://github.com/KestutisKazlauskas/kong-with-metrics-deployment.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
