---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: kong-routes
   namespace: apis
   annotations:
     konghq.com/strip-path: "true"
spec:
   ingressClassName: kong
   rules:
   - http:
      paths:
      - path: /billing
        pathType: ImplementationSpecific
        backend:
          service:
            name: billing
            port:
              number: 80
      - path: /events
        pathType: ImplementationSpecific
        backend:
          service:
            name: events
            port:
              number: 80
