---
apiVersion: v1
kind: Service
metadata:
  namespace: apis
  name: billing
  labels:
    app: billing
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: httpbin

---
apiVersion: v1
kind: Service
metadata:
  namespace: apis
  name: events
  labels:
    app: events
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: go-events-api
