#---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apis
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: kstutisk4/go-api-example:~0.1
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd:repocreds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/KestutisKazlauskas/kong-with-metrics-deployment.git
    targetRevision: main
    path: environments/sandbox/apis
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
