---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-routes
  namespace: kong
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KestutisKazlauskas/kong-with-metrics-deployment.git
    targetRevision: HEAD
    path: environments/sandbox/kong-routes
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
